SPHINX_PROJECT_NAME=LIN Bus Component
VERSION=1.0
DOXYGEN_DIRS=../../../sc_lin/module_lin/src
SOURCE_INCLUDE_DIRS=../../../sc_lin/module_lin/src
XDOC_DIR ?= ../../../xdoc
include $(XDOC_DIR)/Makefile.inc
